#!/bin/bash

#PBS -l walltime=00:05:00
#PBS -l select=2:ncpus=4:ngpus=1:mem=24gb:gpu_type=RTX6000
#PBS -o /rds/general/user/jla21/home/SSL_audio/pbs/out
#PBS -e /rds/general/user/jla21/home/SSL_audio/pbs/err
#PBS -N test

module load anaconda3/personal
source activate project

cd /rds/general/user/jla21/home/SSL_audio

###Number of processes per node to launch
NPROC_PER_NODE=1

MASTER=`/bin/hostname -s`
cat $PBS_NODEFILE>nodelist
###Make sure this node (MASTER) comes first
SLAVES=`cat nodelist | grep -v $MASTER | uniq`

#We want names of master and slave nodes
HOSTLIST="$MASTER $SLAVES"

#Get a random unused port on this host(MASTER)
#First line gets list of unused ports
#3rd line gets single random port from the list
MPORT=`ss -tan | awk '{print $5}' | cut -d':' -f2 | \
        grep "[2-9][0-9]\{3,3\}" | sort | uniq | shuf -n 1`


